tag_mapping = {
    '007': 'bond',
    '007 (series)': 'bond',
    '18th century': 'period piece',
    '1920s': 'period piece',
    '1930s': 'period piece',
    '1950s': 'period piece',
    '1960s': 'period piece',
    '1970s': 'period piece',
    '1980s': 'period piece',
    '19th century': 'period piece',
    '3d': '3d',
    '70mm': 'film format',
    '80s': '1980s',
    '9/11': 'historical event',
    'aardman': 'aardman',
    'aardman studios': 'aardman',
    'abortion': 'abortion',
    'absurd': 'absurd',
    'action': 'action',
    'action packed': 'action',
    'adaptation': 'adaptation',
    'adapted from:book': 'adaptation',
    'adapted from:comic': 'adaptation',
    'adapted from:game': 'adaptation',
    'addiction': 'addiction',
    'adolescence': 'coming of age',
    'adoption': 'adoption',
    'adultery': 'adultery',
    'adventure': 'adventure',
    'affectionate': 'affectionate',
    'afi 100': 'afi 100',
    'afi 100 (laughs)': 'afi 100',
    'afi 100 (movie quotes)': 'afi 100',
    'africa': 'africa',
    'afterlife': 'afterlife',
    'aging': 'aging',
    'aids': 'aids',
    'airplane': 'airplane',
    'airport': 'airport',
    'alaska': 'alaska',
    'alcatraz': 'alcatraz',
    'alcoholism': 'alcoholism',
    'alien': 'aliens',
    'alien invasion': 'aliens',
    'aliens': 'aliens',
    'allegory': 'allegory',
    'almodovar': 'almodovar',
    'alone in the world': 'isolation',
    'alter ego': 'alter ego',
    'alternate endings': 'alternate endings',
    'alternate history': 'alternate history',
    'alternate reality': 'alternate reality',
    'alternate universe': 'alternate reality',
    'amazing cinematography': 'cinematography',
    'amazing photography': 'cinematography',
    'american civil war': 'civil war',
    'amnesia': 'memory loss',
    'amy smart': 'amy smart',
    'android(s)/cyborg(s)': 'androids',
    'androids': 'androids',
    'animal movie': 'animals',
    'animals': 'animals',
    'animated': 'animation',
    'animation': 'animation',
    'anime': 'anime',
    'antarctica': 'antarctica',
    'anti-hero': 'anti-hero',
    'anti-semitism': 'anti-semitism',
    'anti-war': 'anti-war',
    'apocalypse': 'apocalypse',
    'archaeology': 'archaeology',
    'argentina': 'argentina',
    'arms dealer': 'arms dealer',
    'arnold': 'arnold',
    'art': 'art',
    'art house': 'art house',
    'artificial intelligence': 'artificial intelligence',
    'artist': 'artist',
    'artistic': 'artistic',
    'artsy': 'artsy',
    'assassin': 'assassins',
    'assassination': 'assassins',
    'assassins': 'assassins',
    'astronauts': 'space',
    'atheism': 'atheism',
    'atmospheric': 'atmospheric',
    'australia': 'australia',
    'australian': 'australia',
    'author:alan moore': 'author:alan moore',
    'author:neil gaiman': 'author:neil gaiman',
    'autism': 'autism',
    'aviation': 'aviation',
    'awesome': 'awesome',
    'awesome soundtrack': 'great soundtrack',
    'awful': 'awful',
    'bad': 'bad',
    'bad acting': 'bad',
    'bad cgi': 'bad',
    'bad ending': 'bad',
    'bad plot': 'bad',
    'bad science': 'bad',
    'bad script': 'bad',
    'bad sequel': 'bad',
    'ballet': 'ballet',
    'bank robbery': 'bank robbery',
    'baseball': 'baseball',
    'based on a book': 'adaptation',
    'based on a comic': 'adaptation',
    'based on a play': 'adaptation',
    'based on a true story': 'true story',
    'based on a tv show': 'adaptation',
    'based on a video game': 'adaptation',
    'based on book': 'adaptation',
    'based on comic': 'adaptation',
    'based on true story': 'true story',
    'basketball': 'basketball',
    'batman': 'batman',
    'bdsm': 'bdsm',
    'beatles': 'beatles',
    'beautiful': 'beautiful',
    'beautiful scenery': 'beautiful',
    'beautifully filmed': 'beautiful',
    'beauty pageant': 'beauty pageant',
    'beer': 'beer',
    'berlin': 'berlin',
    'best of 2005': 'best of 2005',
    'best war films': 'war',
    'betrayal': 'betrayal',
    'better than expected': 'better than expected',
    'better than the american version': 'better than the american version',
    'biblical': 'christianity',
    'big budget': 'big budget',
    'biographical': 'biography',
    'biography': 'biography',
    'biopic': 'biography',
    'birds': 'animals',
    'biting': 'biting',
    'bittersweet': 'bittersweet',
    'bizarre': 'bizarre',
    'black and white': 'black and white',
    'black comedy': 'dark comedy',
    'blaxploitation': 'blaxploitation',
    'bleak': 'downbeat',
    'blindness': 'blindness',
    'blood': 'blood',
    'bloody': 'blood',
    'boarding school': 'boarding school',
    'boat': 'boat',
    'bollywood': 'bollywood',
    'bombs': 'bombs',
    'bond': 'bond',
    'book': 'book',
    'book was better': 'book',
    'books': 'book',
    'boring': 'boring',
    'boring!': 'boring',
    'boston': 'boston',
    'bowling': 'bowling',
    'boxing': 'boxing',
    'brainwashing': 'brainwashing',
    'brazil': 'brazil',
    'breathtaking': 'breathtaking',
    'brilliant': 'brilliant',
    'british': 'british',
    'british comedy': 'british',
    'broadway': 'broadway',
    'brothers': 'brothers',
    'brutal': 'brutal',
    'brutality': 'brutal',
    'buddy movie': 'buddy movie',
    'bullshit history': 'bullshit history',
    'bullying': 'bullying',
    'business': 'business',
    'c.s. lewis': 'c.s. lewis',
    'california': 'california',
    'camp': 'camp',
    'campy': 'camp',
    'canada': 'canada',
    'cancer': 'cancer',
    'cannibalism': 'cannibalism',
    'caper': 'heist',
    'capitalism': 'capitalism',
    'car chase': 'car chase',
    'carrie-anne moss': 'carrie-anne moss',
    'cars': 'cars',
    'cartoon': 'animation',
    'casino': 'casino',
    'catastrophe': 'catastrophe',
    'cathartic': 'cathartic',
    'catholicism': 'catholicism',
    'censorship': 'censorship',
    'cerebral': 'cerebral',
    'cgi': 'cgi',
    'character study': 'character study',
    'chase': 'chase',
    'cheating': 'cheating',
    'cheerleading': 'cheerleading',
    'cheesy': 'cheesy',
    'chess': 'chess',
    'chicago': 'chicago',
    'chick flick': 'chick flick',
    'child abuse': 'child abuse',
    'childhood': 'childhood',
    'children': 'children',
    'china': 'china',
    'chocolate': 'chocolate',
    'chris tucker': 'chris tucker',
    'christian': 'christianity',
    'christianity': 'christianity',
    'christmas': 'holiday',
    'cia': 'cia',
    'cinematography': 'cinematography',
    'circus': 'circus',
    'civil war': 'civil war',
    'classic': 'classic',
    'classic car': 'classic car',
    'classical music': 'classical music',
    'claustrophobic': 'claustrophobic',
    'claymation': 'claymation',
    'clever': 'clever',
    'clones': 'clones',
    'cloning': 'clones',
    'clowns': 'clowns',
    'coen bros': 'coen brothers',
    'coen brothers': 'coen brothers',
    'cold war': 'cold war',
    'college': 'college',
    'colonialism': 'colonialism',
    'colourful': 'colourful',
    'comedy': 'funny',
    'comic': 'comics',
    'comic book': 'comics',
    'comic book adaption': 'comics',
    'comics': 'comics',
    'coming of age': 'coming of age',
    'coming-of-age': 'coming of age',
    'communism': 'communism',
    'compassionate': 'compassionate',
    'competition': 'competition',
    'complex': 'complex',
    'complex characters': 'complex characters',
    'complicated': 'complicated',
    'complicated plot': 'complicated plot',
    'computer animation': 'animation',
    'computer game': 'video game',
    'computers': 'computers',
    'con artists': 'con men',
    'con men': 'con men',
    'confrontational': 'confrontational',
    'confusing': 'confusing',
    'conspiracy': 'conspiracy',
    'conspiracy theory': 'conspiracy',
    'controversial': 'controversial',
    'cooking': 'cooking',
    'cool': 'cool',
    'corny': 'corny',
    'corporate america': 'corporate america',
    'corruption': 'corruption',
    'costume drama': 'costume drama',
    'courage': 'courage',
    'court': 'court',
    'courtroom': 'court',
    'courtroom drama': 'court',
    'crappy sequel': 'sequels',
    'crazy': 'crazy',
    'creativity': 'creativity',
    'creepy': 'creepy',
    'crime': 'crime',
    'crime gone awry': 'crime',
    'criterion': 'criterion',
    'cross dressing': 'cross dressing',
    'crude humor': 'crude humor',
    'cuba': 'cuba',
    'cult': 'cult',
    'cult classic': 'cult',
    'cult film': 'cult',
    'culture clash': 'culture clash',
    'cute': 'cute',
    'cute!': 'cute',
    'cyberpunk': 'cyberpunk',
    'cyborgs': 'androids',
    'cynical': 'cynical',
    'dance': 'dancing',
    'dancing': 'dancing',
    'dark': 'dark',
    'dark comedy': 'dark comedy',
    'dark fantasy': 'dark fantasy',
    'dark hero': 'dark hero',
    'dark humor': 'dark comedy',
    'dc comics': 'comics',
    'deadpan': 'deadpan',
    'death': 'death',
    'death penalty': 'death penalty',
    'demons': 'demons',
    'depp & burton': 'depp & burton',
    'depressing': 'depressing',
    'depression': 'depression',
    'desert': 'desert',
    'destiny': 'destiny',
    'detective': 'detective',
    'devil': 'devil',
    'dialogue': 'dialogue',
    'dialogue driven': 'dialogue',
    'dinosaurs': 'dinosaurs',
    'directorial debut': 'directorial debut',
    'disability': 'disability',
    'disappointing': 'disappointing',
    'disaster': 'disaster',
    'disney': 'disney',
    'disney animated feature': 'disney',
    'distopia': 'dystopia',
    'disturbing': 'disturbing',
    'divorce': 'divorce',
    'doctors': 'doctors',
    'documentary': 'documentary',
    'dog': 'dogs',
    'dogs': 'dogs',
    'dolphins': 'dolphins',
    'downbeat': 'downbeat',
    'dr. seuss': 'dr. seuss',
    'dragon': 'dragons',
    'dragons': 'dragons',
    'drama': 'drama',
    'dramatic': 'drama',
    'dreamlike': 'surrealism',
    'dreams': 'dreams',
    'dreamworks': 'dreamworks',
    'drinking': 'drinking',
    'drug abuse': 'drug addiction',
    'drug addiction': 'drug addiction',
    'drugs': 'drug addiction',
    'dumb': 'dumb',
    'dumb but funny': 'dumb',
    'dynamic cgi action': 'dynamic cgi action',
    'dysfunctional family': 'family drama',
    'dystopia': 'dystopia',
    'dystopic future': 'dystopia',
    'earnest': 'imdb top 250',
    'easily confused with other movie(s) (title)': 'easily confused with other movie(s) (title)',
    'east germany': 'east germany',
    'eccentricity': 'eccentricity',
    'ecology': 'ecology',
    'educational': 'educational',
    'eerie': 'eerie',
    'effects': 'special effects',
    'egypt': 'egypt',
    'emma watson': 'emma watson',
    'emotional': 'emotional',
    'end of the world': 'apocalypse',
    'england': 'england',
    'enigmatic': 'enigmatic',
    'ennio morricone': 'ennio morricone',
    'enormously long battle scene': 'enormously long battle scene',
    'ensemble cast': 'ensemble cast',
    'entertaining': 'entertaining',
    'entirely dialogue': 'entirely dialogue',
    'environment': 'environment',
    'environmental': 'environment',
    'epic': 'epic',
    'erotic': 'erotic',
    'espionage': 'espionage',
    'ethnic conflict': 'ethnic conflict',
    'evolution': 'evolution',
    'excellent': 'great',
    'excellent script': 'excellent',
    'exceptional acting': 'excellent',
    'exciting': 'exciting',
    'existentialism': 'existentialism',
    'explosions': 'explosions',
    'factual': 'factual',
    'fairy tale': 'fairy tales',
    'fairy tales': 'fairy tales',
    'fake documentary': 'mockumentary',
    'family': 'family',
    'family bonds': 'family bonds',
    'family drama': 'family drama',
    'fantasy': 'fantasy',
    'fantasy world': 'fantasy',
    'farce': 'farce',
    'fascism': 'fascism',
    'fashion': 'fashion',
    'fast paced': 'fast paced',
    'father daughter relationship': 'family drama',
    'father son relationship': 'family drama',
    'father-son relationship': 'family drama',
    'fbi': 'fbi',
    'feel good movie': 'feel-good',
    'feel-good': 'feel-good',
    'fight scenes': 'fight scenes',
    'fighting': 'fighting',
    'fighting the system': 'fighting the system',
    'figure skating': 'figure skating',
    'film noir': 'noir',
    'finnish': 'finnish',
    'firefly': 'firefly',
    'first contact': 'first contact',
    'fish': 'fish',
    'flashbacks': 'flashbacks',
    'food': 'food',
    'football': 'football',
    'forceful': 'forceful',
    'foreign': 'foreign',
    'foul language': 'foul language',
    'fountain of youth': 'fountain of youth',
    'france': 'france',
    'franchise': 'franchise',
    'francis ford copolla': 'francis ford copolla',
    'free speech': 'free speech',
    'free to download': 'free to download',
    'freedom': 'freedom',
    'french': 'france',
    'friendship': 'friendship',
    'frightening': 'frightening',
    'fun': 'fun',
    'fun movie': 'fun',
    'funniest movies': 'funny',
    'funny': 'funny',
    'funny as hell': 'funny',
    'future': 'science fiction',
    'futuristic': 'science fiction',
    'gambling': 'gambling',
    'gangs': 'gangster',
    'gangster': 'gangster',
    'gangsters': 'gangster',
    'gay': 'lgbt',
    'gay character': 'lgbt',
    'geek': 'geek',
    'geeks': 'geek',
    'genetics': 'genetics',
    'genius': 'genius',
    'genocide': 'genocide',
    'george orwell': 'george orwell',
    'german': 'german',
    'germany': 'german',
    'ghosts': 'ghosts',
    'ghosts/afterlife': 'ghosts',
    'giant robots': 'robots',
    'gilliam': 'gilliam',
    'girlie movie': 'girlie movie',
    'glbt': 'lgbt',
    'global warming': 'global warming',
    'god': 'god',
    'golden palm': 'criterion',
    'golf': 'golf',
    'good': 'good',
    'good acting': 'good',
    'good action': 'good',
    'good dialogue': 'good',
    'good music': 'good',
    'good romantic comedies': 'good',
    'good sequel': 'good',
    'good soundtrack': 'good',
    'good story': 'good',
    'good versus evil': 'good versus evil',
    'goofy': 'goofy',
    'gore': 'blood',
    'goretastic': 'blood',
    'gory': 'blood',
    'goth': 'goth',
    'gothic': 'goth',
    'graphic design': 'graphic design',
    'graphic novel': 'graphic novel',
    'gratuitous violence': 'blood',
    'great': 'great',
    'great acting': 'great',
    'great cinematography': 'great',
    'great dialogue': 'great',
    'great ending': 'great',
    'great movie': 'great',
    'great music': 'great',
    'great soundtrack': 'great',
    'greed': 'greed',
    'grim': 'downbeat',
    'grindhouse': 'grindhouse',
    'gritty': 'gritty',
    'gross-out': 'gross-out',
    'gruesome': 'gruesome',
    'guilt': 'guilt',
    'guilty pleasure': 'guilty pleasure',
    'gulf war': 'gulf war',
    'gunfight': 'gunfight',
    'guns': 'guns',
    'gypsy accent': 'gypsy accent',
    'hackers': 'hackers',
    'hacking': 'hackers',
    'halloween': 'halloween',
    'hallucinatory': 'hallucinatory',
    'handycam': 'handycam',
    'hannibal lecter': 'hannibal lecter',
    'happy ending': 'happy ending',
    'hard to watch': 'hard to watch',
    'harry potter': 'harry potter',
    'harsh': 'harsh',
    'haunted house': 'haunted house',
    'hawaii': 'hawaii',
    'heartbreaking': 'emotional',
    'heartwarming': 'heartwarming',
    'heist': 'heist',
    'heroin': 'heroin',
    'heroine': 'heroine',
    'heroine in tight suit': 'heroine',
    'high fantasy': 'high fantasy',
    'high school': 'teenager',
    'highly quotable': 'highly quotable',
    'hilarious': 'funny',
    'hillarious': 'funny',
    'hip hop': 'hip hop',
    'historical': 'history',
    'history': 'history',
    'hit men': 'hitman',
    'hitchcock': 'hitchcock',
    'hitman': 'hitman',
    'holiday': 'holiday',
    'hollywood': 'hollywood',
    'holocaust': 'holocaust',
    'homeless': 'homeless',
    'homophobia': 'lgbt',
    'homosexuality': 'lgbt',
    'honest': 'honest',
    'hong kong': 'hong kong',
    'horrible': 'horrible',
    'horror': 'scary',
    'horses': 'horses',
    'hospital': 'hospital',
    'hostage': 'hostage',
    'hotel': 'hotel',
    'humanity': 'humanity',
    'humor': 'humor',
    'humorous': 'humor',
    'hunting': 'hunting',
    'idealism': 'idealism',
    'identity': 'identity',
    'idiotic': 'idiotic',
    'imaginary friend': 'imaginary friend',
    'imagination': 'imagination',
    'imdb top 250': 'imdb top 250',
    'immigrants': 'immigrants',
    'immortality': 'immortality',
    'incest': 'incest',
    'independent film': 'independent film',
    'india': 'india',
    'indiana jones': 'indiana jones',
    'indians': 'indians',
    'indie': 'indie',
    'infidelity': 'infidelity',
    'innocence lost': 'innocence lost',
    'insanity': 'insanity',
    'inspirational': 'inspirational',
    'inspiring': 'inspirational',
    'intellectual': 'intellectual',
    'intelligent': 'intelligent',
    'intelligent sci-fi': 'intelligent',
    'intense': 'intense',
    'interesting': 'interesting',
    'internet': 'internet',
    'interracial romance': 'interracial romance',
    'intimate': 'intimate',
    'investigation': 'investigation',
    'iran': 'iran',
    'iraq': 'iraq',
    'iraq war': 'iraq',
    'ireland': 'ireland',
    'irish': 'irish',
    'irish accent': 'irish accent',
    'ironic': 'ironic',
    'irreverent': 'irreverent',
    'islam': 'islam',
    'island': 'island',
    'isolation': 'isolation',
    'israel': 'israel',
    'italian': 'italian',
    'italy': 'italy',
    'james bond': 'bond',
    'jane austen': 'jane austen',
    'japan': 'japan',
    'japanese': 'japan',
    'jay and silent bob': 'jay and silent bob',
    'jazz': 'jazz',
    'jesus': 'christianity',
    'jewish': 'jewish',
    'jews': 'jewish',
    'journalism': 'journalism',
    'judaism': 'judaism',
    'jungle': 'jungle',
    'justice': 'justice',
    'kick-butt women': 'heroine',
    'kidnapping': 'kidnapping',
    'kids': 'children',
    'kids and family': 'children',
    'king arthur': 'king arthur',
    'kubrick': 'kubrick',
    'kung fu': 'martial arts',
    'kurosawa': 'kurosawa',
    'lame': 'lame',
    'las vegas': 'las vegas',
    'latin america': 'latin america',
    'lawyer': 'lawyers',
    'lawyers': 'lawyers',
    'lesbian': 'lgbt',
    'lgbtq': 'lgbt',
    'life': 'life',
    'life & death': 'life',
    'life philosophy': 'life philosophy',
    'light': 'light',
    'lions': 'lions',
    'literary adaptation': 'adaptation',
    'literature': 'literature',
    'liv tyler': 'liv tyler',
    'london': 'london',
    'lone hero': 'lone hero',
    'loneliness': 'melancholy',
    'long': 'long',
    'los angeles': 'los angeles',
    'love': 'love',
    'love story': 'love',
    'love triangles': 'love',
    'low budget': 'low budget',
    'lynch': 'lynch',
    'lyrical': 'lyrical',
    'macabre': 'macabre',
    'mad scientist': 'mad scientist',
    'made for tv': 'made for tv',
    'mafia': 'organized crime',
    'magic': 'magic',
    'magic realism': 'magic realism',
    'male nudity': 'nudity',
    'man versus machine': 'man versus machine',
    'manipulation': 'manipulation',
    'marijuana': 'marijuana',
    'marriage': 'marriage',
    'mars': 'space',
    'martial arts': 'martial arts',
    'marvel': 'marvel',
    'marx brothers': 'marx brothers',
    'masterpiece': 'imdb top 250',
    'math': 'math',
    'mathematics': 'math',
    'maze': 'maze',
    'medieval': 'medieval',
    'meditative': 'meditative',
    'melancholic': 'melancholy',
    'melancholy': 'melancholy',
    'memory': 'memory',
    'memory loss': 'memory loss',
    'mental hospital': 'mental hospital',
    'mental illness': 'mental illness',
    'mentor': 'mentor',
    'metaphysics': 'metaphysics',
    'mexico': 'mexico',
    'middle east': 'middle east',
    'midlife crisis': 'midlife crisis',
    'military': 'military',
    'mindfuck': 'mindfuck',
    'mining': 'mining',
    'minnesota': 'minnesota',
    'mission from god': 'mission from god',
    'mistaken identity': 'mistaken identity',
    'miyazaki': 'studio ghibli',
    'mob': 'organized crime',
    'mockumentary': 'mockumentary',
    'modern fantasy': 'fantasy',
    'money': 'money',
    'monkey': 'monkey',
    'monster': 'monsters',
    'monsters': 'monsters',
    'monty python': 'monty python',
    'moody': 'moody',
    'moon': 'space',
    'moral ambiguity': 'moral ambiguity',
    'morality': 'morality',
    'mother daughter relationship': 'family drama',
    'mother-son relationship': 'family drama',
    'motorcycle': 'motorcycle',
    'mountain climbing': 'mountain climbing',
    'movie business': 'movie business',
    'movielens top pick': 'movielens top pick',
    'moving': 'moving',
    'mozart': 'mozart',
    'mtv': 'mtv',
    'multiple storylines': 'multiple storylines',
    'mummy': 'mummy',
    'muppets': 'muppets',
    'murder': 'murder',
    'murder mystery': 'murder mystery',
    'music': 'music',
    'music business': 'music',
    'musical': 'musical',
    'musicians': 'music',
    'mutants': 'mutants',
    'mystery': 'mystery',
    'mythology': 'mythology',
    'narrated': 'narrated',
    'nasa': 'space',
    'native americans': 'native americans',
    'natural disaster': 'natural disaster',
    'nature': 'nature',
    'nazi': 'world war ii',
    'nazis': 'world war ii',
    'neil gaiman': 'author:neil gaiman',
    'neo-nazis': 'neo-nazis',
    'neo-noir': 'noir',
    'nerds': 'nerds',
    'new jersey': 'new jersey',
    'new orleans': 'new orleans',
    'new york': 'new york',
    'new york city': 'new york',
    'new zealand': 'new zealand',
    'ninja': 'ninja',
    'ninjas': 'ninjas',
    'no dialogue': 'no dialogue',
    'no plot': 'no plot',
    'nocturnal': 'nocturnal',
    'noir': 'noir',
    'noir thriller': 'noir',
    'non-hollywood ending': 'non-hollywood ending',
    'non-linear': 'nonlinear',
    'nonlinear': 'nonlinear',
    'nostalgia': 'nostalgia',
    'nostalgic': 'nostalgic',
    'not as good as the first': 'not as good as the first',
    'not funny': 'not funny',
    'notable nudity': 'notable nudity',
    'notable soundtrack': 'great soundtrack',
    'nuclear': 'nuclear',
    'nuclear bomb': 'nuclear',
    'nuclear war': 'nuclear war',
    'nudity': 'nudity',
    'nudity (full frontal - brief)': 'nudity',
    'nudity (full frontal - notable)': 'nudity',
    'nudity (full frontal)': 'nudity',
    'nudity (rear)': 'nudity',
    'nudity (topless - brief)': 'nudity',
    'nudity (topless - notable)': 'nudity',
    'nudity (topless)': 'nudity',
    'obsession': 'obsession',
    'ocean': 'ocean',
    'off-beat comedy': 'off-beat comedy',
    'office': 'office',
    'oil': 'oil',
    'olympics': 'olympics',
    'ominous': 'ominous',
    'opera': 'opera',
    'organized crime': 'organized crime',
    'original': 'original',
    'original plot': 'original',
    'orphans': 'orphans',
    'oscar': 'imdb top 250',
    'oscar (best actor)': 'imdb top 250',
    'oscar (best actress)': 'imdb top 250',
    'oscar (best animated feature)': 'imdb top 250',
    'oscar (best cinematography)': 'imdb top 250',
    'oscar (best directing)': 'imdb top 250',
    'oscar (best editing)': 'imdb top 250',
    'oscar (best effects - visual effects)': 'imdb top 250',
    'oscar (best foreign language film)': 'imdb top 250',
    'oscar (best music - original score)': 'imdb top 250',
    'oscar (best music - original song)': 'imdb top 250',
    'oscar (best picture)': 'imdb top 250',
    'oscar (best sound)': 'imdb top 250',
    'oscar (best supporting actor)': 'imdb top 250',
    'oscar (best supporting actress)': 'imdb top 250',
    'oscar (best writing - screenplay written directly for the screen)': 'imdb top 250',
    'oscar winner': 'imdb top 250',
    'over the top': 'over the top',
    'overrated': 'overrated',
    'palestine': 'palestine',
    'parallel universe': 'alternate reality',
    'paranoia': 'paranoia',
    'paranoid': 'paranoia',
    'parenthood': 'parenthood',
    'paris': 'paris',
    'parody': 'parody',
    'passionate': 'passionate',
    'penguins': 'penguins',
    'perfect': 'perfect',
    'period piece': 'period piece',
    'peter pan': 'peter pan',
    'pg': 'pg',
    'pg-13': 'pg-13',
    'philip k. dick': 'philip k. dick',
    'philosophical': 'philosophy',
    'philosophy': 'philosophy',
    'photographer': 'photographer',
    'photography': 'photography',
    'pigs': 'animals',
    'pirates': 'pirates',
    'pixar': 'pixar',
    'pixar animation': 'pixar',
    'plot': 'plot',
    'plot holes': 'plot holes',
    'plot twist': 'twist',
    'poetry': 'poetry',
    'poignant': 'poignant',
    'pointless': 'pointless',
    'poker': 'poker',
    'poland': 'poland',
    'police': 'police',
    'police corruption': 'police corruption',
    'police investigation': 'police investigation',
    'political': 'political',
    'political corruption': 'political corruption',
    'politics': 'political',
    'pornography': 'pornography',
    'post apocalyptic': 'apocalypse',
    'post-apocalyptic': 'apocalypse',
    'potential oscar nom': 'oscar',
    'poverty': 'poverty',
    'powerful ending': 'great ending',
    'predictable': 'predictable',
    'pregnancy': 'pregnancy',
    'prejudice': 'prejudice',
    'prequel': 'prequel',
    'president': 'president',
    'pretentious': 'pretentious',
    'prison': 'prison',
    'prison escape': 'prison escape',
    'private detective': 'detective',
    'product placement': 'product placement',
    'prohibition': 'prohibition',
    'propaganda': 'propaganda',
    'prostitution': 'prostitution',
    'psychedelic': 'psychedelic',
    'psychiatrist': 'psychiatrist',
    'psychiatry': 'psychiatry',
    'psychological': 'psychology',
    'psychology': 'psychology',
    'pulp': 'pulp',
    'punk': 'punk',
    'puppets': 'puppets',
    'queer': 'lgbt',
    'quirky': 'quirky',
    'quotable': 'quotable',
    'rabbits': 'animals',
    'race': 'race',
    'race issues': 'race',
    'racing': 'racing',
    'racism': 'racism',
    'radio': 'radio',
    'rags to riches': 'rags to riches',
    'rape': 'rape',
    'rats': 'animals',
    'realistic': 'realistic',
    'realistic action': 'realistic',
    'reality tv': 'reality tv',
    'rebellion': 'rebellion',
    'redemption': 'redemption',
    'reflective': 'melancholy',
    'relationships': 'relationships',
    'religion': 'religion',
    'remade': 'remade',
    'remake': 'remake',
    'revenge': 'revenge',
    'revolution': 'revolution',
    'ridiculous': 'ridiculous',
    'rio de janeiro': 'rio de janeiro',
    'road movie': 'road movie',
    'road trip': 'road movie',
    'roald dahl': 'roald dahl',
    'robbery': 'robbery',
    'robert downey jr': 'robert downey jr',
    'robert ludlum': 'robert ludlum',
    'robot': 'robots',
    'robots': 'robots',
    'rock and roll': 'rock and roll',
    'romance': 'romance',
    'romantic': 'romance',
    'romantic comedy': 'romantic comedy',
    'rome': 'rome',
    'runaway': 'runaway',
    'russia': 'russia',
    'russian': 'russian',
    'sacrifice': 'sacrifice',
    'sad': 'emotional',
    'sad but good': 'emotional',
    'samurai': 'samurai',
    'san francisco': 'san francisco',
    'sappy': 'sappy',
    'sarcasm': 'sarcasm',
    'satire': 'satire',
    'satirical': 'satire',
    'saturday night live': 'saturday night live',
    'saturn award (best science fiction film)': 'saturn award',
    'saturn award (best special effects)': 'saturn award',
    'scary': 'scary',
    'scenic': 'scenic',
    'schizophrenia': 'mental illness',
    'school': 'school',
    'sci fi': 'science fiction',
    'sci-fi': 'science fiction',
    'science': 'science',
    'science fiction': 'science fiction',
    'scifi': 'science fiction',
    'scifi cult': 'science fiction',
    'scotland': 'scotland',
    'screwball': 'screwball comedy',
    'screwball comedy': 'screwball comedy',
    'script': 'script',
    'secret service': 'secret service',
    'secrets': 'secrets',
    'segregation': 'segregation',
    'self discovery': 'self discovery',
    'sentimental': 'sentimental',
    'sequel': 'sequels',
    'sequels': 'sequels',
    'serial killer': 'serial killer',
    'series': 'series',
    'sex': 'sex',
    'sex comedy': 'sex comedy',
    'sexual': 'sexual',
    'sexual abuse': 'sexual abuse',
    'sexuality': 'sexuality',
    'sexualized violence': 'sexualized violence',
    'sexy': 'sexy',
    'shakespeare': 'shakespeare',
    'shallow': 'shallow',
    'shark': 'animals',
    'shopping': 'shopping',
    'short': 'short',
    'short-term memory loss': 'memory loss',
    'silent': 'silent',
    'silly': 'silly',
    'silly fun': 'silly',
    'simple': 'simple',
    'single father': 'single parent',
    'sisters': 'sisters',
    'skinhead': 'skinhead',
    'slackers': 'slackers',
    'slapstick': 'slapstick',
    'slasher': 'slasher',
    'slavery': 'slavery',
    'slow': 'slow',
    'slow paced': 'slow',
    'small town': 'small town',
    'snakes': 'animals',
    'so bad it\'s funny': 'so bad it\'s good',
    'so bad it\'s good': 'so bad it\'s good',
    'soccer': 'soccer',
    'social commentary': 'social commentary',
    'solitude': 'solitude',
    'sophia coppola': 'sophia coppola',
    'south africa': 'south africa',
    'south america': 'south america',
    'southern theme': 'southern theme',
    'space': 'space',
    'space opera': 'space',
    'space program': 'space',
    'space travel': 'space',
    'spaghetti western': 'spaghetti western',
    'spain': 'spain',
    'spanish': 'spanish',
    'spanish civil war': 'spanish civil war',
    'special': 'special',
    'special effects': 'special effects',
    'spelling bee': 'spelling bee',
    'spiders': 'animals',
    'spielberg': 'spielberg',
    'spies': 'espionage',
    'splatter': 'splatter',
    'spock': 'star trek',
    'spoof': 'parody',
    'sports': 'sports',
    'spy': 'espionage',
    'spying': 'espionage',
    'stage magic': 'stage magic',
    'stand-up comedy': 'stand-up comedy',
    'star trek': 'star trek',
    'star wars': 'star wars',
    'steampunk': 'steampunk',
    'stereotypes': 'stereotypes',
    'stoner movie': 'stoner movie',
    'stop motion': 'stop motion',
    'stop-motion': 'stop motion',
    'story': 'story',
    'storytelling': 'storytelling',
    'stranded': 'stranded',
    'strange': 'strange',
    'strippers': 'strippers',
    'studio ghibli': 'studio ghibli',
    'stunning': 'stunning',
    'stupid': 'stupid',
    'stupid as hell': 'stupid',
    'stupidity': 'stupidity',
    'stylish': 'stylish',
    'stylized': 'stylish',
    'submarine': 'submarine',
    'suburbia': 'suburbia',
    'suicide': 'suicide',
    'suicide attempt': 'suicide',
    'super hero': 'comics',
    'super-hero': 'comics',
    'superhero': 'comics',
    'superheroes': 'comics',
    'supernatural': 'supernatural',
    'suprisingly clever': 'suprisingly clever',
    'surfing': 'surfing',
    'surprise ending': 'twist ending',
    'surreal': 'surrealism',
    'surrealism': 'surrealism',
    'surveillance': 'surveillance',
    'survival': 'survival',
    'suspense': 'thriller',
    'suspenseful': 'thriller',
    'swashbuckler': 'swashbuckler',
    'swedish': 'swedish',
    'sweet': 'sweet',
    'switching places': 'switching places',
    'sword fight': 'sword fighting',
    'sword fighting': 'sword fighting',
    'talking animals': 'animals',
    'talky': 'talky',
    'tarantino': 'tarantino',
    'teacher': 'teacher',
    'tear jerker': 'tear jerker',
    'technology': 'technology',
    'teen': 'teenager',
    'teen movie': 'teenager',
    'teenager': 'teenager',
    'teenagers': 'teenager',
    'teens': 'teenager',
    'teleportation': 'teleportation',
    'television': 'television',
    'tense': 'tense',
    'terminal illness': 'terminal illness',
    'terrorism': 'terrorism',
    'texas': 'texas',
    'thought-provoking': 'thought-provoking',
    'thriller': 'thriller',
    'time': 'time',
    'time loop': 'time loop',
    'time travel': 'time travel',
    'tokyo': 'japan',
    'tolkien': 'tolkien',
    'tom clancy': 'tom clancy',
    'too long': 'too long',
    'too short': 'too short',
    'torture': 'torture',
    'touching': 'emotional',
    'toys': 'toys',
    'tragedy': 'tragedy',
    'train': 'trains',
    'trains': 'trains',
    'transformation': 'transformation',
    'transgender': 'transgender',
    'travel': 'travel',
    'treasure': 'treasure',
    'treasure hunt': 'treasure hunt',
    'tricky': 'tricky',
    'trilogy': 'trilogy',
    'true story': 'true story',
    'truman capote': 'truman capote',
    'twist': 'twist',
    'twist ending': 'twist',
    'twists & turns': 'twist',
    'undercover cop': 'undercover cop',
    'underdog': 'underdog',
    'underrated': 'underrated',
    'understated': 'understated',
    'underwater': 'underwater',
    'unfunny': 'unfunny',
    'unintentionally funny': 'unintentionally funny',
    'unique': 'unique',
    'united nations': 'united nations',
    'unlikeable characters': 'unlikeable characters',
    'unlikely friendships': 'friendship',
    'unrealistic': 'unrealistic',
    'unusual plot structure': 'unusual plot structure',
    'us history': 'history',
    'utopia': 'utopia',
    'vampire': 'vampires',
    'vampire human love': 'vampires',
    'vampires': 'vampires',
    'vengeance': 'revenge',
    'very funny': 'funny',
    'very good': 'great',
    'very interesting': 'very interesting',
    'video game': 'video game',
    'video game adaptation': 'video game',
    'video games': 'video game',
    'videogame': 'video game',
    'vienna': 'vienna',
    'vietnam': 'vietnam',
    'vietnam war': 'vietnam',
    'view askew': 'view askew',
    'vigilante': 'vigilante',
    'vigilantism': 'vigilante',
    'violence': 'brutal',
    'violent': 'brutal',
    'virginity': 'virginity',
    'virtual reality': 'virtual reality',
    'virus': 'virus',
    'visceral': 'visceral',
    'visual': 'visual',
    'visually appealing': 'visual',
    'visually stunning': 'visual',
    'visuals': 'visuals',
    'voodoo': 'voodoo',
    'voyeurism': 'voyeurism',
    'war': 'war',
    'war movie': 'war',
    'wartime': 'war',
    'waste of time': 'waste of time',
    'watch the credits': 'watch the credits',
    'weapons': 'weapons',
    'wedding': 'wedding',
    'weed': 'marijuana',
    'weird': 'weird',
    'werewolf': 'werewolves',
    'werewolves': 'werewolves',
    'western': 'western',
    'whimsical': 'whimsical',
    'wilderness': 'wilderness',
    'wine': 'wine',
    'wistful': 'wistful',
    'witch': 'witches',
    'witches': 'witches',
    'witty': 'witty',
    'wizards': 'wizards',
    'women': 'women',
    'working class': 'working class',
    'workplace': 'workplace',
    'world politics': 'world politics',
    'world war i': 'world war i',
    'world war ii': 'world war ii',
    'writer\'s life': 'writers',
    'writers': 'writers',
    'writing': 'writing',
    'wuxia': 'wuxia',
    'wwii': 'world war ii',
    'zombie': 'zombies',
    'zombies': 'zombies',
}
