high_corr_pairs = {
    'lgbtq': 'lgbt',
    'lgbt': 'lgbtq',
    'criterion': 'downbeat',
    'downbeat': 'criterion',
    'criterion': 'enigmatic',
    'enigmatic': 'criterion',
    'organized crime': 'gangster',
    'gangster': 'organized crime',
    'emotional': 'heartbreaking',
    'heartbreaking': 'emotional',
    'war': 'world war i',
    'world war i': 'war',
    'jesus': 'christianity',
    'christianity': 'jesus',
    'surrealism': 'strange',
    'strange': 'surrealism',
    'great': 'very good',
    'very good': 'great',
    'grim': 'downbeat',
    'downbeat': 'grim',
    'imdb top 250': 'great',
    'great': 'imdb top 250',
    'emotional': 'touching',
    'touching': 'emotional',
    'melancholy': 'criterion',
    'criterion': 'melancholy',
    'melancholy': 'reflective',
    'reflective': 'melancholy',
}
